[tool.black]
line-length = 120
target-version = ['py38', 'py39', 'py310', 'py311', 'py312']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | venv
  | _build
  | buck-out
  | build
  | dist
  | node_modules
)/
'''

[tool.pylint.FORMAT]
indent-string = "    "
max-line-length = 120

[tool.pylint.MASTER]
disable = [
  #"line-too-long",
  #"missing-function-docstring",
  #"missing-module-docstring",
  #"too-few-public-methods",
]
ignore = [".venv"]

[tool.ruff]
# By default Ruff enable all checks, so do nothing here
# select = [...]

# Specify files/directories to exclude (e.g., virtualenv or generated files)
exclude = [".venv", "__pycache__", "static", "templates"]

# Specify the maximum line length for the code
line-length = 120

# Add any ignored rules (e.g., if you want to skip specific linter checks)
lint.ignore = [
  #"E501", # line-too-long
]

[tool.ruff.format]
indent-style = "space"
